provider default@no-ip.com {
hostname = clearwater1601.myddns.me
username = 'st_lim+noip@stlim.net'
password = '9xaw!q4s$!jRSxG'
wildcard = true
checkip-command = 'getrealip.sh'
}
iterations = 1
iface = eth3
ca-trust-file = /etc/ssl/certs/ca-certificates.crt
