[".oh-my-zsh"]
type = "archive"
url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
exact = false
exclude = ["**/custom/**"]
refreshPeriod = "168h"
stripComponents = 1
[".config/wezterm/colors"]
type = "git-repo"
url = "https://github.com/lysyi3m/macos-terminal-themes.git"
refreshPeriod = "168h"
[".config/nvim"]
# type = "git-repo"
# url = "https://github.com/LazyVim/starter"
type = "archive"
url = "https://github.com/LazyVim/starter/archive/refs/heads/main.tar.gz"
exact = false
refreshPeriod = "168h"
