#!/bin/zsh

# Hide the “default interactive shell is now zsh” warning on macOS.
export BASH_SILENCE_DEPRECATION_WARNING=1;

# Make vim the default editor.
export EDITOR=nvim

# Avoid issues with `gpg` as installed via Homebrew.
# https://stackoverflow.com/a/42265848/96656
export GPG_TTY=$(tty);

# Increase Bash history size. Allow 32³ entries; the default is 500.
export HISTSIZE=32768
export HISTFILESIZE=${HISTSIZE}
# Omit duplicates and commands that begin with a space from history.
export HISTCONTROL=ignoreboth

# Prefer US English and use UTF-8.
export LANG='en_US.UTF-8';
export LC_ALL='en_US.UTF-8';

# Highlight section titles in manual pages.
export LESS_TERMCAP_md="${yellow}";

# Don’t clear the screen after quitting a manual page.
# export MANWIDTH=$(( $COLUMNS -7 ))
# export PAGER='less -FNRX';
# export MANPAGER='less -FNRX';
export MANPAGER="sh -c 'col -bx | bat -l man -p'";
export SSLKEYLOGFILE="/tmp/sslkeylogfile.txt"
