#!/usr/bin/env zsh
# mise 
start_time=$(gdate +%s%3N)
eval "$($(brew --prefix)/bin/mise activate zsh)"
end_time=$(gdate +%s%3N)
time_taken=$((end_time - start_time))
echo "Load mise...${time_taken}ms...Done"

# Make Python use UTF-8 encoding for output to stdin, stdout, and stderr.
export PYTHONIOENCODING='UTF-8';

# PATH extension
PATH=${HOME}/.cargo/bin:${PATH}
# PATH=${JAVA_HOME}/bin:${PATH}
export PATH 

# Added by Antigravity
export PATH="/Users/st_lim/.antigravity/antigravity/bin:$PATH"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
alias claude-mem='/Users/st_lim/.bun/bin/bun "/Users/st_lim/.claude/plugins/cache/thedotmack/claude-mem/10.6.0/scripts/worker-service.cjs"'                                      │    │
