# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: https
# What editor gh should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor:
# When to interactively prompt. This is a global config that cannot be overridden by hostname. Supported values: enabled, disabled
prompt: enabled
# A pager program to send command output to, e.g. "less". Set the value to "cat" to disable the pager.
pager: delta -s
# Aliases allow you to create nicknames for gh commands
aliases:
  co: pr checkout
  gmpr: pr create --title "[Graymail] $1" --label msp-graymail --template pull_request_template.md
  gm-airflow-prod: '!gh workflow run deploy_graymail_airflow_prod.yml --ref=$(git symbolic-ref --short HEAD);sleep 10;gh_out=$(gh run list --user assweet --workflow=deploy_graymail_airflow_prod.yml -L 2 --json "headBranch,databaseId,startedAt,status"); echo $gh_out; gh run watch $(echo $gh_out | jq ".[0].databaseId")'
  gm-test: workflow run publish_bento_image_ecr.yml -F bento_target=email/graymail/graymail -F environments=test -F region_stratos_lite=true
  gm-test-watch: '!gh_out=$(gh run list --user assweet --workflow=publish_bento_image_ecr.yml -L 2 --json "headBranch,databaseId,startedAt,status"); echo $gh_out; gh run watch $(echo $gh_out | jq ".[0].databaseId")'
  gm-prod: workflow run publish_bento_image_ecr.yml -F bento_target=email/graymail/graymail -F environments=prod -F region_eu=true -F region_us=true -F region_us_legacy=true -F region_apso1=true
  gm-stratos: '!gh workflow run deploy_graymail_stratos.yml --ref=$(git symbolic-ref --short HEAD);sleep 10;gh_out=$(gh run list --user assweet --workflow=deploy_graymail_stratos.yml -L 2 --json "headBranch,databaseId,startedAt,status"); echo $gh_out; gh run watch $(echo $gh_out | jq ".[0].databaseId")'
  gm-reports-api-test: '!gh workflow run deploy_graymail_reports_api_test.yml --ref=$(git symbolic-ref --short HEAD);sleep 10; gh_out=$(gh run list --user assweet --workflow=publish_bento_image_ecr.yml -L 2 --json "headBranch,databaseId,startedAt,status"); echo $gh_out; gh run watch $(echo $gh_out | jq ".[0].databaseId")'
  prls: pr list --author '@me'
# The path to a unix socket through which send HTTP connections. If blank, HTTP traffic will be handled by net/http.DefaultTransport.
http_unix_socket:
# What web browser gh should use when opening URLs. If blank, will refer to environment.
browser:
version: "1"
