# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: https
# What editor gh should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor:
# When to interactively prompt. This is a global config that cannot be overridden by hostname. Supported values: enabled, disabled
prompt: enabled
# A pager program to send command output to, e.g. "less". Set the value to "cat" to disable the pager.
pager:
# Aliases allow you to create nicknames for gh commands
aliases:
    co: pr checkout
    integration-handler-staging: workflow run deploy_integration_handler_staging.yml
    integration-handler-prod: workflow run deploy_integration_handler_prod.yml
    internalapp-staging: workflow run deploy_internal_app_staging.yml -f service_name=staging-1
    internalapp-prod: 'workflow run deploy_internal_app_prod.yml '
    prls: pr list --author '@me'
    onboarding-app-prod: workflow run deploy_onboarding_app_prod.yml
    onboarding-app-staging: workflow run deploy_onboarding_app_staging.yml
# The path to a unix socket through which send HTTP connections. If blank, HTTP traffic will be handled by net/http.DefaultTransport.
http_unix_socket:
# What web browser gh should use when opening URLs. If blank, will refer to environment.
browser:
