[tools]
bun = "latest"
node = "lts"
python = "3.12"
uv = "latest"

[env]
_.python.venv = { create = false, path = ".venv", uv_create_args = [
  "--seed",
  "--system-site-packages",
] }
UV_PYTHON = { value = "{{ tools.python.path }}", tools = true }

[settings]
python.uv_venv_auto = "source"

[settings.npm]
package_manager = "bun"
