return {
  g = {
    ["test#python#runner"] = 'pytest',
    indent_blankline_char_list = {'|', '¦', '┆', '┊'},
    solarized_italics = 1,
    tokyonight_italic_functions = true,
    tokyonight_sidebars = { "qf", "vista_kind", "terminal", "packer" },
    tokyonight_style = "night",
  },
  opt = {
    cmdheight = 1,
    colorcolumn = "80",
    conceallevel = 2,
    expandtab = true,
    foldenable = false,
    foldexpr = "nvim_treesitter#foldexpr()",
    foldmethod = 'expr',
    guifont = "JetbrainsMono Nerd Font Mono:14;FiraCode Nerd Font:14",
    linebreak = true,
    list = true,
    listchars = { tab = "│→", extends = "⟩", precedes = "⟨", trail = "·", nbsp = "␣" },
    relativenumber = true,
    sessionoptions = "curdir,folds,help,options,tabpages,winsize,resize,winpos,terminal",
    shiftwidth = 2,
    softtabstop = 2,
    tabstop = 2,
    termguicolors = true,
    undofile = false,
    wrap = true,
  },
}
